import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {startAutoScrape} from "./api/utils/autoScrape.js"
import Nav from "./navbar/Nav.jsx"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Events ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  startAutoScrape()
  return (
    <html lang="en">
       <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          />
        </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
